name: deploy

on:
  push:
    branches: [main, feature/deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      front_directory: front
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
          cache-dependency-path: front/yarn.lock

      - run: yarn install --frozen-lockfile
        working-directory: ${{ env.front_directory }}

      - run: yarn build
        env:
          CI: false
        working-directory: ${{ env.front_directory }}

      - run: |
          git config --global user.email "deploy@gmail.com"
          git config --global user.name "deploy"
          git add .
          git commit -m "set build data"

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "server"