name: deploy

on:
  push:
    branches: [main, feature/deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      front_directory: front
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - run: npm ci
        working-directory: ${{ env.front_directory }}

      - run: npm run build
        working-directory: ${{ env.front_directory }}

      - run: ls server/src/main/resources/static

      # - name: deploy to heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}